package be.uliege.boigelot.oop.sokoban.main.cells;

public enum CellType {BLACK, CRATE, CRATE2, EMPTY, PLAYERDOWN, PLAYERUP, PLAYERLEFT, PLAYERRIGHT, TARGET, WALL, 
	PLAYERONTARGETDOWN, PLAYERONTARGETUP, PLAYERONTARGETLEFT, PLAYERONTARGETRIGHT,
    MAGMA, LAVA, PLAYERONLAVADOWN, PLAYERONLAVAUP, PLAYERONLAVALEFT, PLAYERONLAVARIGHT, 
	PLAYERINMAGMADOWN, PLAYERINMAGMAUP, PLAYERINMAGMALEFT, PLAYERINMAGMARIGHT, 
    NUMBER0, NUMBER1, NUMBER2, NUMBER3, NUMBER4, NUMBER5, NUMBER6, NUMBER7, NUMBER8, NUMBER9}
