package be.uliege.boigelot.oop.sokoban.main.levels;

import be.uliege.boigelot.oop.sokoban.main.cells.CellType;

public class Levels {
	
	private final static CellType BLACK = CellType.BLACK;
	private final static CellType CRATE = CellType.CRATE;
	private final static CellType CRATE2 = CellType.CRATE2;
    private final static CellType EMPTY = CellType.EMPTY;
    private final static CellType PLAYER = CellType.PLAYERDOWN;
    private final static CellType TARGET = CellType.TARGET;
    private final static CellType WALL = CellType.WALL;
	private final static CellType MAGMA = CellType.MAGMA;
	private final static CellType LAVA = CellType.LAVA;
    private final static CellType COUNTER = CellType.NUMBER0;
	
	private static CellType[][] levelGrid;
	
	public Levels(int level){
		switch(level) {
			case 2:
		    	CellType[][]level2 = {
							{BLACK,BLACK,WALL,WALL,WALL,WALL,WALL,WALL,BLACK,BLACK},
							{BLACK,BLACK,WALL,TARGET,EMPTY,CRATE,PLAYER,WALL,BLACK,BLACK},
							{BLACK,BLACK,WALL,WALL,EMPTY,CRATE,EMPTY,WALL,BLACK,BLACK},
							{BLACK,BLACK,WALL,EMPTY,EMPTY,WALL,WALL,WALL,BLACK,BLACK},
							{BLACK,BLACK,WALL,EMPTY,EMPTY,EMPTY,TARGET,WALL,BLACK,BLACK},	
							{BLACK,BLACK,WALL,MAGMA,MAGMA,LAVA,MAGMA,WALL,BLACK,BLACK},
                            {BLACK,BLACK,WALL,MAGMA,MAGMA,LAVA,MAGMA,WALL,BLACK,BLACK},
                            {BLACK,BLACK,WALL,TARGET,CRATE,EMPTY,EMPTY,WALL,BLACK,BLACK},
                            {BLACK,BLACK,WALL,WALL,WALL,WALL,WALL,WALL,BLACK,BLACK},	
							{BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,COUNTER}
							};
	    		levelGrid = level2;
			    break;

            case 3:
			    CellType [][]level3 = {
							{BLACK,BLACK,BLACK,WALL,WALL,WALL,WALL,WALL,BLACK,BLACK},
							{BLACK,WALL,WALL,WALL,EMPTY,EMPTY,EMPTY,WALL,BLACK,BLACK},
							{BLACK,WALL,TARGET,PLAYER,CRATE,EMPTY,EMPTY,WALL,BLACK,BLACK},
							{BLACK,WALL,WALL,WALL,EMPTY,CRATE,TARGET,WALL,BLACK,BLACK},
							{BLACK,WALL,TARGET,WALL,WALL,CRATE,EMPTY,WALL,BLACK,BLACK},
							{BLACK,WALL,EMPTY,WALL,EMPTY,TARGET,EMPTY,WALL,WALL,BLACK},
							{BLACK,WALL,CRATE,EMPTY,CRATE2,CRATE,CRATE,TARGET,WALL,BLACK},
							{BLACK,WALL,EMPTY,EMPTY,EMPTY,TARGET,EMPTY,EMPTY,WALL,BLACK},
							{BLACK,WALL,WALL,WALL,WALL,WALL,WALL,WALL,WALL,BLACK},
							{BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,COUNTER}
							};
		    	levelGrid = level3;
    			break;
			
			case 1:
		    	CellType[][]level1 = {
							{BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK},
							{BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK},
							{BLACK,BLACK,WALL,WALL,WALL,WALL,WALL,WALL,BLACK,BLACK},
							{BLACK,BLACK,WALL,TARGET,EMPTY,CRATE,PLAYER,WALL,BLACK,BLACK},
							{BLACK,BLACK,WALL,WALL,EMPTY,CRATE,EMPTY,WALL,BLACK,BLACK},
							{BLACK,BLACK,WALL,EMPTY,EMPTY,WALL,WALL,WALL,BLACK,BLACK},
							{BLACK,BLACK,WALL,EMPTY,EMPTY,EMPTY,TARGET,WALL,BLACK,BLACK},
							{BLACK,BLACK,WALL,WALL,WALL,WALL,WALL,WALL,BLACK,BLACK},	
							{BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK},		
							{BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,COUNTER}
							};
	    		levelGrid = level1;
			    break;

			case 0:
			    CellType[][]level0 = {
							{BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK},
							{BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK},
							{BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK},
							{BLACK,WALL,WALL,WALL,WALL,WALL,WALL,WALL,BLACK,BLACK}, 
							{BLACK,WALL,PLAYER,EMPTY,CRATE,EMPTY,TARGET,WALL,BLACK,BLACK},
							{BLACK,WALL,WALL,WALL,WALL,WALL,WALL,WALL,BLACK,BLACK},
							{BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK},
							{BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK},
							{BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK},
							{BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,BLACK,COUNTER}
							};
			    levelGrid = level0;
			    break;
			
			default:
			    break;
		}
	}
	
	public CellType getGridCell(int x, int y){
		return levelGrid[x][y];
	}
}